# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: standard_window_fns.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='standard_window_fns.proto',
  package='org.apache.beam.runner_api.v1',
  syntax='proto3',
  serialized_pb=_b('\n\x19standard_window_fns.proto\x12\x1dorg.apache.beam.runner_api.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"j\n\x13\x46ixedWindowsPayload\x12\'\n\x04size\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12*\n\x06offset\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x97\x01\n\x15SlidingWindowsPayload\x12\'\n\x04size\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12*\n\x06offset\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12)\n\x06period\x18\x03 \x01(\x0b\x32\x19.google.protobuf.Duration\">\n\x0fSessionsPayload\x12+\n\x08gap_size\x18\x01 \x01(\x0b\x32\x19.google.protobuf.DurationB9\n$org.apache.beam.sdk.common.runner.v1B\x11StandardWindowFnsb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_FIXEDWINDOWSPAYLOAD = _descriptor.Descriptor(
  name='FixedWindowsPayload',
  full_name='org.apache.beam.runner_api.v1.FixedWindowsPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='org.apache.beam.runner_api.v1.FixedWindowsPayload.size', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='org.apache.beam.runner_api.v1.FixedWindowsPayload.offset', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=231,
)


_SLIDINGWINDOWSPAYLOAD = _descriptor.Descriptor(
  name='SlidingWindowsPayload',
  full_name='org.apache.beam.runner_api.v1.SlidingWindowsPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='size', full_name='org.apache.beam.runner_api.v1.SlidingWindowsPayload.size', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='org.apache.beam.runner_api.v1.SlidingWindowsPayload.offset', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='period', full_name='org.apache.beam.runner_api.v1.SlidingWindowsPayload.period', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=385,
)


_SESSIONSPAYLOAD = _descriptor.Descriptor(
  name='SessionsPayload',
  full_name='org.apache.beam.runner_api.v1.SessionsPayload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gap_size', full_name='org.apache.beam.runner_api.v1.SessionsPayload.gap_size', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=387,
  serialized_end=449,
)

_FIXEDWINDOWSPAYLOAD.fields_by_name['size'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_FIXEDWINDOWSPAYLOAD.fields_by_name['offset'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SLIDINGWINDOWSPAYLOAD.fields_by_name['size'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_SLIDINGWINDOWSPAYLOAD.fields_by_name['offset'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SLIDINGWINDOWSPAYLOAD.fields_by_name['period'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_SESSIONSPAYLOAD.fields_by_name['gap_size'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
DESCRIPTOR.message_types_by_name['FixedWindowsPayload'] = _FIXEDWINDOWSPAYLOAD
DESCRIPTOR.message_types_by_name['SlidingWindowsPayload'] = _SLIDINGWINDOWSPAYLOAD
DESCRIPTOR.message_types_by_name['SessionsPayload'] = _SESSIONSPAYLOAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FixedWindowsPayload = _reflection.GeneratedProtocolMessageType('FixedWindowsPayload', (_message.Message,), dict(
  DESCRIPTOR = _FIXEDWINDOWSPAYLOAD,
  __module__ = 'standard_window_fns_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.beam.runner_api.v1.FixedWindowsPayload)
  ))
_sym_db.RegisterMessage(FixedWindowsPayload)

SlidingWindowsPayload = _reflection.GeneratedProtocolMessageType('SlidingWindowsPayload', (_message.Message,), dict(
  DESCRIPTOR = _SLIDINGWINDOWSPAYLOAD,
  __module__ = 'standard_window_fns_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.beam.runner_api.v1.SlidingWindowsPayload)
  ))
_sym_db.RegisterMessage(SlidingWindowsPayload)

SessionsPayload = _reflection.GeneratedProtocolMessageType('SessionsPayload', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONSPAYLOAD,
  __module__ = 'standard_window_fns_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.beam.runner_api.v1.SessionsPayload)
  ))
_sym_db.RegisterMessage(SessionsPayload)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n$org.apache.beam.sdk.common.runner.v1B\021StandardWindowFns'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
